! Black
URxvt*color0:   #303030
URxvt*color8:   #5F5F5F

! Red
URxvt*color1:   #c03000
URxvt*color9:   #FF3A78

! Green
URxvt*color2:   #b1d631
URxvt*color10:  #A6CD07

! Yellow
URxvt*color3:   #fecf35
URxvt*color11:  #B5C865

! Blue
URxvt*color4:   #426870
URxvt*color12:  #4A7781

! Magenta
URxvt*color5:   #6D506D
URxvt*color13:  #FF3B77

! Cyan
URxvt*color6:   #4bb5c1
URxvt*color14:  #4bb5c1

! White
URxvt*color7:   #e2e2e5
URxvt*color15:  #e2e2e5

! vim: et sw=2 syn=xdefaults
