!kuro
URxvt*color0:#2a1d17
URxvt*color8:#4f362b

!aka
URxvt*color1:#da1657
URxvt*color9:#da4375

!midori
URxvt*color2:#3ea250
URxvt*color10:#6cb87a

!kiiro
URxvt*color3:#e3d33d
URxvt*color11:#e3da84

!ao
URxvt*color4:#3ea290
URxvt*color12:#8ca8a3

!momoiro
URxvt*color5:#ff850d
URxvt*color13:#ffa64f

!mizuiro
URxvt*color6:#8c16da
URxvt*color14:#a167c7

!shiro
URxvt*color7:#e9e9e9
URxvt*color15:#fdfdfd
